lint:
  actions_awsfulltest: false
  files_exist:
    - .github/ISSUE_TEMPLATE/config.yml
    - CODE_OF_CONDUCT.md
    - assets/nf-core-downloadsnpeffcache_logo_light.png
    - conf/modules.config
    - conf/test_full.config
    - docs/images/nf-core-downloadsnpeffcache_logo_dark.png
    - docs/images/nf-core-downloadsnpeffcache_logo_light.png
  modules_config: false
  multiqc_config: false
  nextflow_config:
    - params.input
  nf_test_content: false
nf_core_version: 3.5.1
repository_type: pipeline
template:
  author: Maxime U Garcia
  description: Download SnpEff cache for annotation-cache
  force: false
  is_nfcore: false
  name: downloadsnpeffcache
  org: annotation-cache
  outdir: .
  skip_features: []
  version: "105"
