lint:
  actions_ci: false
  files_exist:
    - .github/ISSUE_TEMPLATE/config.yml
    - .github/workflows/awsfulltest.yml
    - .github/workflows/awstest.yml
    - CODE_OF_CONDUCT.md
    - assets/multiqc_config.yml
    - assets/nf-core-downloadsnpeffcache_logo_light.png
    - conf/igenomes.config
    - conf/modules.config
    - conf/test_full.config
    - docs/images/nf-core-downloadsnpeffcache_logo_dark.png
    - docs/images/nf-core-downloadsnpeffcache_logo_light.png
    - lib/WorkflowDownloadsnpeffcache.groovy
  files_unchanged:
    - CODE_OF_CONDUCT.md
    - assets/nf-core-downloadsnpeffcache_logo_light.png
    - docs/images/nf-core-downloadsnpeffcache_logo_light.png
    - docs/images/nf-core-downloadsnpeffcache_logo_dark.png
    - .github/ISSUE_TEMPLATE/bug_report.yml
  multiqc_config:
    - report_comment
  nextflow_config:
    - manifest.name
    - manifest.homePage
    - params.input
  schema_lint: false
nf_core_version: 3.3.2
repository_type: pipeline
template:
  author: Maxime U Garcia
  description: Download SnpEff cache for annotation-cache
  force: false
  is_nfcore: false
  name: downloadsnpeffcache
  org: annotation-cache
  outdir: .
  skip_features: []
  version: "105"
